#
###################################
# Site wide configuration
####################################
#
title: Pilar Huidobro
email: huidobropilar@gmail.com
description: Cute adventures in games and code
url: # althaire.github.io


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Vienna
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Pilar Huidobro
  avatar: avatar.png
  job: Fullstack Developer
  bio: Software engineer at Chill Bill. Organizer at Ruby Habits and Vienna.css [Avid gamer and craftsy person!] Absolutely in love with all tech ✨
  email: huidobropilar@gmail.com
  disqus-shortname:
  twitter: Althaire
  facebook: pilar.huidobro
  google:
    plus: PilarHuidobroPeltier
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: Althaire
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: pilar-huidobro-961abbab
  xing: #username
  instagram: princesspilar
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: Althaire
  dribbble: #username
  youtube: #username
  soundcloud: espeon-766049116
  weibo: #username
  flickr: #username
  500px: #username
  codepen: Althaire
